version: 2
updates:
- package-ecosystem: npm
  directory: "/desktop"
  schedule:
    interval: weekly
    time: '13:00'
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "eslint*"
      update-types: ["version-update:semver-major"]
    - dependency-name: "@babel/*"
      update-types: ["version-update:semver-major"]
    - dependency-name: "@typescript-eslint/*"
      update-types: ["version-update:semver-major"]
    - dependency-name: "@types/*"
- package-ecosystem: npm
  directory: "/js/js-flipper"
  schedule:
    interval: weekly
    time: '13:00'
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "eslint*"
      update-types: ["version-update:semver-major"]
    - dependency-name: "@babel/*"
      update-types: ["version-update:semver-major"]
    - dependency-name: "@typescript-eslint/*"
      update-types: ["version-update:semver-major"]
    - dependency-name: "@types/*"
- package-ecosystem: npm
  directory: "/react-native/ReactNativeFlipperExample"
  schedule:
    interval: weekly
    time: '13:00'
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "eslint*"
      update-types: ["version-update:semver-major"]
    - dependency-name: "@babel/*"
      update-types: ["version-update:semver-major"]
    - dependency-name: "@typescript-eslint/*"
      update-types: ["version-update:semver-major"]
    - dependency-name: "@types/*"
- package-ecosystem: npm
  directory: "/react-native/react-native-flipper"
  schedule:
    interval: weekly
    time: '13:00'
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "eslint*"
      update-types: ["version-update:semver-major"]
    - dependency-name: "@babel/*"
      update-types: ["version-update:semver-major"]
    - dependency-name: "@typescript-eslint/*"
      update-types: ["version-update:semver-major"]
    - dependency-name: "@types/*"
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    time: '13:00'
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/android"
  schedule:
    interval: weekly
    time: '13:00'
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/android/tutorial"
  schedule:
    interval: weekly
    time: '13:00'
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/android/sample"
  schedule:
    interval: weekly
    time: '13:00'
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/android/no-op"
  schedule:
    interval: weekly
    time: '13:00'
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/android/plugins/fresco"
  schedule:
    interval: weekly
    time: '13:00'
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/android/plugins/network"
  schedule:
    interval: weekly
    time: '13:00'
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/android/plugins/litho"
  schedule:
    interval: weekly
    time: '13:00'
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/android/plugins/leakcanary"
  schedule:
    interval: weekly
    time: '13:00'
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/android/plugins/leakcanary2"
  schedule:
    interval: weekly
    time: '13:00'
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/packer"
  schedule:
    interval: weekly
    time: '13:00'
  open-pull-requests-limit: 10
