version: 2.1
executors:
  default-executor:
    docker:
      - image: circleci/android:api-29-ndk
    resource_class: large

    environment:
      _JAVA_OPTIONS: "-Xmx1500m -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"
      TERM: 'dumb'

jobs:
  snapshot:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: install retry
          command: scripts/install-retry.sh
        command: scripts/install-retry.sh
      - run:
          name: build and deploy
          command: |
            yes | sdkmanager "platforms;android-27" || true
            /tmp/retry -m 3 ./gradlew :android:assembleRelease
            /tmp/retry -m 3 scripts/publish-android-snapshot.sh
  release:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: install retry
          command: scripts/install-retry.sh
      - run:
          name: build and deploy
          command: |
            yes | sdkmanager "platforms;android-27" || true
            /tmp/retry -m 3 ./gradlew :android:assembleRelease
            /tmp/retry -m 3 scripts/publish-android-release.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - snapshot:
          filters:
            branches:
              only: master
      - release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
