version: 2.1
executors:
  default-executor:
    docker:
      - image: circleci/android:api-29-ndk
    resource_class: large

    environment:
      _JAVA_OPTIONS: "-Xmx1500m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"
      TERM: 'dumb'

jobs:
  snapshot:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: build and deploy
          command: |
            yes | sdkmanager "platforms;android-27" || true
            ./gradlew :android:assembleRelease && scripts/publish-android-snapshot.sh
  release:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: build and deploy
          command: |
            yes | sdkmanager "platforms;android-27" || true
            ./gradlew :android:assembleRelease && scripts/publish-android-release.sh
  publish-pods:
    macos:
      xcode: "10.2.1"
    steps:
      - checkout
      - run: curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: "Pod version"
          command: |
            pod --version
      - run:
          name: "Push Flipper Pod"
          command: |
            pod trunk push ./Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation
      - run:
          name: "Repo update"
          command: |
            pod repo update
      - run:
          name: "Push FlipperKit Pod"
          command: |
            pod trunk push ./FlipperKit.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - snapshot:
          filters:
            branches:
              only: master
      - release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish-pods:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
