[package]
name = "flipper-packer"
description = "Helper tool that breaks down a Flipper release into smaller artifacts."
license = "MIT"
repository = "https://github.com/facebook/flipper.git"
keywords = ["flipper", "cli"]
categories = ["development-tools"]
version = "0.2.1"
authors = ["Facebook, Inc."]
edition = "2018"

[dependencies]
clap = "2.33.3"
shellexpand = "2.1.0"
tar = "0.4.33"
serde = { version = "1.0.124", features = ["derive"] }
serde_yaml = "0.8.17"
anyhow = "1.0.38"
sha2 = "0.9.3"
data-encoding = "2.3.2"
serde_json = "1.0.64"
rayon = "1.5.0"
indicatif = "0.15.0"
xz2 = "0.1.6"

[dev-dependencies]
tempdir = "0.3.7"
