name: Build iOS apps
on: [push, pull_request]
jobs:
  build-sample-objc:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: iOS/Sample

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pod install --repo-update
      - name: Build Sample app
        run: |
          IPHONESIMULATOR=$(xcodebuild -showsdks | grep -o "iphonesimulator[0-9]\\+\\.[0-9]\\+$") && echo $IPHONESIMULATOR
          xcodebuild build -workspace Sample.xcworkspace -scheme Sample -sdk $IPHONESIMULATOR EXCLUDED_ARCHS=arm64

  build-sample-swift:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: iOS/SampleSwift

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pod install --repo-update
      - name: Build SampleSwift app
        run: |
          IPHONESIMULATOR=$(xcodebuild -showsdks | grep -o "iphonesimulator[0-9]\\+\\.[0-9]\\+$") && echo $IPHONESIMULATOR
          xcodebuild build -workspace SampleSwift.xcworkspace -scheme SampleSwift -sdk $IPHONESIMULATOR

  build-tutorial:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: iOS/Tutorial

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pod install --repo-update
      - name: Build Tutorial app
        run: |
          IPHONESIMULATOR=$(xcodebuild -showsdks | grep -o "iphonesimulator[0-9]\\+\\.[0-9]\\+$") && echo $IPHONESIMULATOR
          xcodebuild build -workspace Tutorial.xcworkspace -scheme Tutorial -sdk $IPHONESIMULATOR -arch x86_64
