name: Validate Podspecs
# This action runs on 'git push' and PRs to below specified paths.
on:
  push:
    paths:
      - "iOS/**"
      - "xplat/**"
      - "Flipper.podspec"
      - "FlipperKit.podspec"
      - "iOS-pod-lint.yml"
  pull_request:
    paths:
      - "iOS/**"
      - "xplat/**"
      - "Flipper.podspec"
      - "FlipperKit.podspec"
      - "iOS-pod-lint.yml"

jobs:
  lint-flipperkit_fbdefines_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FBDefines
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FBDefines --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_core_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/Core
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: pod lib lint FlipperKit.podspec --subspec=FlipperKit/Core --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_cppbridge_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/CppBridge
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: pod lib lint FlipperKit.podspec --subspec=FlipperKit/CppBridge --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_dynamic_convert_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FBCxxFollyDynamicConvert
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FBCxxFollyDynamicConvert --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_port_forwarding_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FKPortForwarding
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FKPortForwarding --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_layout_highlight_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FlipperKitHighlightOverlay
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FlipperKitHighlightOverlay --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_layout_text_searchable_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FlipperKitHighlightOverlay
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FlipperKitLayoutTextSearchable --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_layout_helpers_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FlipperKitLayoutHelpers
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FlipperKitLayoutHelpers --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_layout_ios_descriptors_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FlipperKitLayoutIOSDescriptors
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FlipperKitLayoutIOSDescriptors --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_layout_plugin_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FlipperKitLayoutPlugin
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FlipperKitLayoutPlugin --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_layout_ck_plugin_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FlipperKitLayoutComponentKitSupport
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FlipperKitLayoutComponentKitSupport --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_network_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FlipperKitNetworkPlugin
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FlipperKitNetworkPlugin --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_skiosnetwork_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/SKIOSNetworkPlugin
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: pod lib lint FlipperKit.podspec --subspec=FlipperKit/SKIOSNetworkPlugin --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_user_default_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FlipperKitUserDefaultsPlugin
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FlipperKitUserDefaultsPlugin --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_example_plugin_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FlipperKitExamplePlugin
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FlipperKitExamplePlugin --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipperkit_react_plugin_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Install Dependences
        run: pod repo update
      - name: Lint FlipperKit/FlipperKitReactPlugin
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: pod lib lint FlipperKit.podspec --subspec=FlipperKit/FlipperKitReactPlugin --include-podspecs=Flipper.podspec --use-libraries --allow-warnings --verbose --skip-import-validation

  lint-flipper_pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Install Dependences
        run: pod repo update
      - name: Lint Flipper
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: pod lib lint Flipper.podspec --use-libraries --allow-warnings --verbose
