name: PKG Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      pkg-directory: ./desktop/pkg

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: install
      working-directory: ${{env.pkg-directory}}
      run: yarn
    - name: run
      working-directory: ${{env.pkg-directory}}
      run: bin/run
