name: Publish NPM
# This action runs on 'git push tag v*'
on:
  push:
    tags:
      - v*
  workflow_dispatch:

defaults:
  run:
    working-directory: desktop/

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: '18.x'
      - name: Install
        run: yarn
      - name: Set versions
        run: yarn bump-versions
      - name: Set up npm token
        run: echo "//registry.yarnpkg.com/:_authToken=${{ secrets.FLIPPER_NPM_TOKEN }}" >> ~/.npmrc
      - name: Publish packages
        run: yarn publish-packages
      - name: Publish React Native
        run: yarn publish
        working-directory: react-native/react-native-flipper
      - name: Publish JS Flipper
        working-directory: js/js-flipper
        run: |
          yarn
          yarn build
          yarn publish
